---
title: CIUFLA XXXIV\par Gênese de Latossolos via Sensores Próximos
author: Marcelo Mancini, Lucas Benedet, Anita Teixeira, Sérgio Henrique Silva, Luiz Roberto Guimarães Guilherme, Nilton Curi
date: 29-10-2021
fontsize: 10pt
width: 150mm
geometry:
    textwidth=150mm
indent: 0pt
abstract_title: Resumo
keyword_title: Palavras-chave
keywords:
    - Solos Tropicais
    - pXRF
    - Vis-NIR
    - Oxisols
    - Morphometrics
output:
    Sorte::abstract_template:
        latex_engine: xelatex
---

Latossolos constituem a classe de solo de maior expressão geográfica do Brasil.
É caracterizada por solos muito desenvolvidos e intemperizados. Apesar de ser a
classe mais comum, sua elevada profundidade devido ao longo tempo de formação
inibe estudos mais detalhados sobre a variação de seus atributos ao longo dos
profundos perfis. Aqui, o objetivo é auxiliar neste contexto através de novas
tecnologias: os sensores próximos. Dois perfis de Latossolos localizados no
campus da UFLA foram amostrados seguindo um grid de 10 x 10 cm, totalizando 100
amostras por perfil. As amostras foram submetidas à análise de dois sensores: o
espectrômetro portátil de fluorescência de raios-X (pXRF) e o espectroscópio de
reflectância difusa nas faixas do visível e infravermelho próximo (Vis-NIR).
Nas análises por pXRF, cada amostra foi analisada por 60 s e, posteriormente,
os teores dos elementos químicos foram espacializados ao longo dos perfis
utilizando-se o método Multilevel B-Splines. As análises por Vis-NIR ocorreram
por horizonte, sendo as amostras escaneadas por 10 s cada, resultando em 100
leituras por amostra, cuja média fora calculada. Os resultados demonstraram que
os sensores são capazes de identificar com êxito a variação química através dos
perfis, mesmo destes solos muito intemperizados e aparentemente homogêneos. Os
espectros fornecidos pelo Vis-NIR detectaram diferentes intensidades de
reflectância em cada horizonte. Os espectros destacaram a maior presença de
hematita no Latossolo Vermelho e de caulinita no Latossolo Vermelho-Amarelo. As
diferenças de reflectância entre horizontes foram maiores no Latossolo
Vermelho-Amarelo. A distribuição de concentrações dos elementos químicos ao
longo dos perfis demonstrara variação significativa. Faixas de acúmulo de Si e
Al puderam ser identificadas entre os horizontes B1 e B2 no Latossolo Vermelho,
e um maior grau de intemperismo foi identificado no Latossolo Vermelho-Amarelo,
indicando sua formação acima de um material pré-intemperizado. Os sensores
próximos mostram-se ferramentas valiosas para viabilizar o estudo detalhado de
solos tropicais que, apesar de possuírem aparência homogênea, revelam traços
químicos variáveis e ricos em informações sobre seus processos de formação.
